### ISSUE TITLE
Simple README.md includes url for data and how to run example

### ISSUE THREAD

**Issue by javadba** [deeplearning4j/deeplearning4j-word2vec-examples#1]
Please provide simple README.md doc that includes url for example word vectors to run the example plus command line to run it: also expected results would be helpful

**Comment by agibsonccc** [comment]
Will do! This was more for testing.

**Comment by linkerlin** [comment]
+1
Would you update the pom so we can run it?

**Comment by agibsonccc** [comment]
You can also just send a PR ;) I don't have the banwdith to update all the examples all over the place atm. We are focused on centralizing on the dl4j-0.4-examples for things that aren't spark.
